#!/usr/bin/env bash
# /opt/wonderbear/coordination/auto-commit.sh
#
# 自动 commit 当前 release 分支的改动
# 关键: 用 git diff 找 droid 这次改动了什么,精确 add(不用 -A 防垃圾)
#
# 用法: bash auto-commit.sh <wo_id> [risk_level]
# 输出: COMMIT_SHA=<sha>

set -uo pipefail
WO_ID="${1:?用法: $0 <wo_id> [risk_level]}"
RISK_LEVEL="${2:-L2}"

cd /opt/wonderbear || exit 1

CURRENT_BRANCH=$(git branch --show-current)
LOG_TAG="[auto-commit][$WO_ID][$RISK_LEVEL]"
echo "$LOG_TAG 当前分支: $CURRENT_BRANCH"

# 安全栏: 必须在 release 分支
if [[ "$CURRENT_BRANCH" != release/* ]]; then
  echo "$LOG_TAG ❌ 当前不在 release 分支,拒绝自动 commit"
  echo "$LOG_TAG 请先 git checkout release/showroom-20260429"
  exit 1
fi

# 看是否有改动
if git diff --quiet && git diff --staged --quiet; then
  # 看 untracked 是不是工单需要的(比如 droid 创建了新文件)
  UNTRACKED=$(git status --short | grep '^??' | wc -l)
  if [ "$UNTRACKED" -eq 0 ]; then
    echo "$LOG_TAG ℹ️  无任何改动,跳过 commit"
    echo "COMMIT_SHA=$(git rev-parse HEAD)"
    exit 0
  fi
fi

# === 精确 add: 只 add 工单 scope 内的文件 ===
# 策略: 如果工单 README 列了改动 scope, 严格按 scope add
#       否则, 按 git diff 找出 modified 文件 + 在 scope 白名单内的 untracked

# 默认 scope 白名单(基于 WO-3.X 工单类型)
SCOPE_PATTERNS=(
  "tv-html/src/"
  "tv-html/public/"
  "h5/src/"
  "server-v7/src/"
  "server-v7/prisma/"
  "coordination/done/${WO_ID}-report.md"
)

# 加 modified 文件(只在 scope 内)
echo "$LOG_TAG === 选择性 git add ==="
ADDED_COUNT=0
git diff --name-only | while read -r f; do
  for pat in "${SCOPE_PATTERNS[@]}"; do
    case "$f" in
      $pat*|$pat)
        git add "$f"
        echo "$LOG_TAG  + $f"
        break
        ;;
    esac
  done
done
git diff --staged --name-only | while read -r f; do
  echo "$LOG_TAG  + (staged) $f"
done
# 加 untracked 在 scope 内的(droid 新建的文件)
git status --short | grep '^??' | awk '{print $2}' | while read -r f; do
  for pat in "${SCOPE_PATTERNS[@]}"; do
    case "$f" in
      $pat*|$pat)
        git add "$f"
        echo "$LOG_TAG  + (untracked) $f"
        break
        ;;
    esac
  done
done

# 检查最终是否有 staged
if git diff --staged --quiet; then
  echo "$LOG_TAG ⚠️  scope 内无 staged 改动,跳过 commit"
  echo "COMMIT_SHA=$(git rev-parse HEAD)"
  exit 0
fi

# 列出最终要 commit 的文件
STAGED_LIST=$(git diff --staged --name-only | head -10)
echo "$LOG_TAG === 即将 commit 的文件 ==="
echo "$STAGED_LIST"

# 详细 commit message
COMMIT_MSG="auto: $WO_ID via WonderBear coordinator [$RISK_LEVEL]

工单: $WO_ID (Risk-Level: $RISK_LEVEL)
报告: /opt/wonderbear/coordination/done/${WO_ID}-report.md
verify: /opt/wonderbear/coordination/workorders/${WO_ID}/${WO_ID}-verify.sh
部署目标: /var/www/wonderbear-tv
钉钉验收: 发 \"通过 $WO_ID\" 接受 / \"回滚 $WO_ID\" 撤回

改动文件:
$(echo "$STAGED_LIST" | sed 's/^/  - /')

回滚命令(自动 + 手动两种):
  自动: bash /opt/wonderbear/coordination/rollback-wo.sh $WO_ID
  手动: git -C /opt/wonderbear revert HEAD --no-edit && git push origin $CURRENT_BRANCH

Generated by: WonderBear auto-coordinator
Commit-Time: $(date -Iseconds)
"

git commit -m "$COMMIT_MSG"
COMMIT_SHA=$(git rev-parse HEAD)
echo "$LOG_TAG ✅ commit 创建: $COMMIT_SHA"

# Push release 分支
echo "$LOG_TAG === push origin $CURRENT_BRANCH ==="
git push origin "$CURRENT_BRANCH" 2>&1 | tail -10
PUSH_RC="${PIPESTATUS[0]}"
if [ "$PUSH_RC" -ne 0 ]; then
  echo "$LOG_TAG ⚠️  push 失败 (rc=$PUSH_RC) — commit 已留在本地"
  echo "COMMIT_SHA=$COMMIT_SHA"
  exit 0
fi

echo "$LOG_TAG ✅ push release 分支成功"

# 如果是 L1 全自动,接着 push main
if [ "$RISK_LEVEL" = "L1" ]; then
  echo "$LOG_TAG === L1 全自动 — 自动 push main ==="
  bash /opt/wonderbear/coordination/approve-to-main.sh "$WO_ID" "$COMMIT_SHA"
  APPROVE_RC=$?
  if [ "$APPROVE_RC" -ne 0 ]; then
    echo "$LOG_TAG ⚠️  approve-to-main 失败 (rc=$APPROVE_RC),release 分支已 push 但 main 未合并"
    echo "$LOG_TAG    人工合并: bash approve-to-main.sh $WO_ID $COMMIT_SHA"
  fi
fi

echo "COMMIT_SHA=$COMMIT_SHA"
exit 0
